from building import *

cwd = GetCurrentDir()

CPPPATH = [cwd]
CPPDEFINES=['D45', 'HPM6750']

# add the general drivers
src = Split("""
    board.c
    rtt_board.c
    pinmux.c
    hpm_wm8960.c
""")

if GetDepend('RT_USING_FAL'):
    src += ['fal_flash_port.c']
    
if GetDepend('BSP_USING_RW007'):
    src += ['rw007_port.c']

if GetDepend('BSP_USING_FS'):
    src += ['filesystem.c']

if GetDepend('BSP_USING_TOUCH_GT9147'):
    src += ['gt9147_config.c']

if GetDepend('BSP_USING_LVGL'):
    CPPPATH += [os.path.join(cwd, 'lvgl')]
    src += ['lvgl/lv_port_disp.c']
    src += ['lvgl/lv_port_indev.c']
    
if GetDepend('BSP_USING_CAMERA'):
    src += ['cam_config.c']

if GetDepend('BSP_USING_JPEG'):
    CPPPATH += [os.path.join(cwd, 'jpeg')]
    src += ['jpeg/jpeg_config.c']

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
